#pragma once
#include <transform.hpp>
#include <vmhandlers.hpp>
#include <vmp2.hpp>
#include <vmprofiles.hpp>
#include <vminstrs.hpp>
#include <vmctx.hpp>
#include <vmutils.hpp>
#include <calc_jmp.hpp>
#include <vmlocate.hpp>
#include <virtual_machine_stream.hpp>
#define NOMINMAX
#include "../../easylogging++.h"
#include "../../ScopeExit.h"